service: chat-middleware

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2

functions:
  express_server:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
